USE [master]
GO

/****** Object: Database [TasksDB] ******/
CREATE DATABASE [TasksDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TasksDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TasksDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TasksDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TasksDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TasksDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TasksDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TasksDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TasksDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TasksDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TasksDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TasksDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TasksDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TasksDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TasksDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TasksDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TasksDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TasksDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TasksDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TasksDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TasksDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TasksDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TasksDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TasksDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TasksDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TasksDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TasksDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TasksDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TasksDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TasksDB] SET  MULTI_USER 
GO
ALTER DATABASE [TasksDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TasksDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TasksDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TasksDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TasksDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TasksDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TasksDB] SET QUERY_STORE = OFF
GO
ALTER DATABASE [TasksDB] SET  READ_WRITE 
GO

USE [TasksDB]
GO
/****** Object: Table [dbo].[TaskTypes] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TaskTypes](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](MAX) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [TasksDB]
GO
/****** Object: Table [dbo].[TaskStatuses] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TaskStatuses](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](256) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [TasksDB]
GO
/****** Object: Table [dbo].[OpportunityStatuses] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OpportunityStatuses](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](MAX) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [TasksDB]
GO
/****** Object: Table [dbo].[Contacts] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contacts](
	[Id] [int] NOT NULL,
	[Email] [nvarchar](256) NOT NULL,
	[Company] [nvarchar](256) NULL,
	[LastName] [nvarchar](256) NULL,
	[FirstName] [nvarchar](256) NULL,
	[Phone] [nvarchar](256) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [TasksDB]
GO
/****** Object: Table [dbo].[Opportunities] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Opportunities](
	[Id] [int] NOT NULL,
	[Amount] [money] NOT NULL,
	[UserId] [nvarchar](450) NULL,
	[ContactId] [int] NOT NULL,
	[StatusId] [int] NOT NULL,
	[CloseDate] [datetime] NOT NULL,
	[Name] [nvarchar](256) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Opportunities]  WITH CHECK ADD FOREIGN KEY([ContactId])
REFERENCES [dbo].[Contacts] ([Id])
GO
ALTER TABLE [dbo].[Opportunities]  WITH CHECK ADD FOREIGN KEY([StatusId])
REFERENCES [dbo].[OpportunityStatuses] ([Id])
GO

USE [TasksDB]
GO
/****** Object: Table [dbo].[Tasks] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tasks](
	[Id] [int] NOT NULL,
	[Title] [nvarchar](256) NULL,
	[OpportunityId] [int] NOT NULL,
	[DueDate] [datetime] NOT NULL,
	[TypeId] [int] NOT NULL,
	[StatusId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tasks]  WITH CHECK ADD FOREIGN KEY([OpportunityId])
REFERENCES [dbo].[Opportunities] ([Id])
GO
ALTER TABLE [dbo].[Tasks]  WITH CHECK ADD FOREIGN KEY([TypeId])
REFERENCES [dbo].[TaskTypes] ([Id])
GO
ALTER TABLE [dbo].[Tasks]  WITH CHECK ADD FOREIGN KEY([StatusId])
REFERENCES [dbo].[TaskStatuses] ([Id])
GO